const Discord = require('discord.js')
const axios = require('axios')

module.exports.liste = function(message) {
    axios.get("https://api.warframestat.us/pc/nightwave")
        .then((response) => {
            console.log("\n\n")
            console.log(response)
            let embed = new Discord.RichEmbed()
                .setTitle("**__Nightwaves__**")
                .setURL("https://semlar.com/challenges")
                .setThumbnail("https://vignette.wikia.nocookie.net/warframe/images/e/e0/NightwaveSyndicate.png/revision/latest?cb=20190228190906")
                .addField(response.data.activeChallenges[0].title + " (" + response.data.activeChallenges[0].reputation + ") :", response.data.activeChallenges[0].desc)
                .addField(response.data.activeChallenges[1].title + " (" + response.data.activeChallenges[1].reputation + ") :", response.data.activeChallenges[1].desc)
                .addField(response.data.activeChallenges[2].title + " (" + response.data.activeChallenges[2].reputation + ") :", response.data.activeChallenges[2].desc)
                .addField(response.data.activeChallenges[3].title + " (" + response.data.activeChallenges[3].reputation + ") :", response.data.activeChallenges[3].desc)
                .addField(response.data.activeChallenges[4].title + " (" + response.data.activeChallenges[4].reputation + ") :", response.data.activeChallenges[4].desc)
                .addField(response.data.activeChallenges[5].title + " (" + response.data.activeChallenges[5].reputation + ") :", response.data.activeChallenges[5].desc)
                .addField(response.data.activeChallenges[6].title + " (" + response.data.activeChallenges[6].reputation + ") :", response.data.activeChallenges[6].desc)
                .addField(response.data.activeChallenges[7].title + " (" + response.data.activeChallenges[7].reputation + ") :", response.data.activeChallenges[7].desc)
                .addField(response.data.activeChallenges[8].title + " (" + response.data.activeChallenges[8].reputation + ") :", response.data.activeChallenges[8].desc)
                .addField(response.data.activeChallenges[9].title + " (" + response.data.activeChallenges[9].reputation + ") :", response.data.activeChallenges[9].desc)
            message.channel.send(embed)
        }).catch(function () {
            let embed = new Discord.RichEmbed()
                .setTitle("Une erreur est survenue !")
                .setDescription("Contactez un " + message.guild.roles.find("name", "Developper").name + " pour corriger ce problème.")
            message.channel.send(embed)
        })
}